#!/usr/bin/env python3
"""Bundle ES modules into one file for file:// (double-click index.html)."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "app.bundle.js"

# Dependency order: leaves first, then dependents, main last.
FILES = [
    "core/constants.js",
    "core/version.js",
    "core/store.js",
    "utils/text.js",
    "utils/dates.js",
    "utils/names.js",
    "utils/dom.js",
    "ui/status-banner.js",
    "ui/fairness-panel.js",
    "ui/excel-grid-view.js",
    "features/analysis.js",
    "features/auto-scheduler.js",
    "features/search.js",
    "features/vacations.js",
    "features/undo-redo.js",
    "features/export-html.js",
    "features/google-sheet.js",
    "features/shift-requirements.js",
    "features/grid.js",
    "ui/schedule-view.js",
    "ui/toolbar.js",
    "ui/layout.js",
    "core/state-sync.js",
    "main.js",
]

IMPORT_RE = re.compile(r"^import\s+[\s\S]*?;\s*\n?", re.MULTILINE)
EXPORT_BLOCK_RE = re.compile(r"^export\s*\{[\s\S]*?\};\s*\n?", re.MULTILINE)


def strip_module_syntax(source: str) -> str:
    source = IMPORT_RE.sub("", source)
    source = EXPORT_BLOCK_RE.sub("", source)
    source = re.sub(r"\bexport\s+(?=function|const|let|var|class|async)", "", source)
    return source.strip() + "\n"


def main() -> None:
    parts = [
        "// guard_roster standalone bundle — generated by tools/bundle_standalone.py\n",
        "// Re-run build-standalone.bat after editing source modules.\n\n",
    ]
    for rel in FILES:
        path = ROOT / rel
        if not path.exists():
            raise SystemExit(f"Missing: {path}")
        body = strip_module_syntax(path.read_text(encoding="utf-8"))
        parts.append(f"// ----- {rel} -----\n")
        parts.append(body)
        parts.append("\n")
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
